trigger:
- main

pool:
  vmImage: 'windows-latest'   # Better for .NET builds

steps:
# Install .NET SDK 
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '9.0.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

# Restore NuGet packages
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'Backend/*.sln'

# Build solution
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'Backend/*.sln'
    arguments: '--configuration Release'

# Run XUnit tests
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'Backend/XUnitTests/*.csproj'
    arguments: '--configuration Release --no-build --collect:"XPlat Code Coverage"'
