trigger:
- main

pool:
  vmImage: 'windows-latest'   # Windows is safer for full .NET SDKs

steps:
# Install .NET 9 SDK explicitly
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '9.0.x'
    includePreviewVersions: true
    installationPath: $(Agent.ToolsDirectory)/dotnet

# Restore NuGet packages
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'Backend/*.sln'

# Build solution
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'Backend/*.sln'
    arguments: '--configuration Release'

# Run XUnit tests and collect coverage
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'Backend/XUnitTests/*.csproj'
    arguments: '--configuration Release --no-build --collect:"XPlat Code Coverage"'
    publishTestResults: true
